@startuml ComponentesArquitectura

' Diagrama de Componentes - Arquitectura Pipes & Filters (solo CLI)

skinparam componentStyle rectangle

title Arquitectura CLI - MainPipeline y filtros standalone

package "CLI" {
  [MainPipeline] as C_Main
}

package "Motor (SO)" {
  [PipelineManager] as C_PipelineManager
}

package "DTO / Datos" {
  [PaqueteDatos] as C_Datos
  [TipoDato] as C_TipoDato
  [ProtocoloPipe] as C_Protocolo
}

package "Filtros standalone (JAR)" {
  [ID1_CargarArchivoStandalone]
  [ID2_TextoABinarioStandalone]
  [ID3_FiltroImagenesStandalone]
  [ID4_BinarioABase64Standalone]
  [ID5_Base64ABinarioStandalone]
  [ID6_EncriptarSHA256Standalone]
  [ID7_BuscarPalabraStandalone]
  [ID8_ContarOcurrenciasStandalone]
}

' Relaciones principales CLI
C_Main --> C_PipelineManager : construye pasos\n(PasoFiltro)
C_Main --> C_Datos : crea entrada inicial\n(PaqueteDatos)
C_Main --> C_TipoDato

C_PipelineManager --> C_Protocolo : usa para stdin/stdout
C_PipelineManager --> C_Datos     : pasa paquetes entre filtros

[ID1_CargarArchivoStandalone] --> C_Protocolo
[ID2_TextoABinarioStandalone] --> C_Protocolo
[ID3_FiltroImagenesStandalone] --> C_Protocolo
[ID4_BinarioABase64Standalone] --> C_Protocolo
[ID5_Base64ABinarioStandalone] --> C_Protocolo
[ID6_EncriptarSHA256Standalone] --> C_Protocolo
[ID7_BuscarPalabraStandalone] --> C_Protocolo
[ID8_ContarOcurrenciasStandalone] --> C_Protocolo

@enduml

